# Generated by Django 4.0.1 on 2022-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('NS', 'Не указано')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
