# Generated by Django 4.0.1 on 2022-02-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_comments_alter_profile_image_reply_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('NS', 'Не указано')], default='NS', max_length=2),
        ),
    ]
